# Generated by Django 5.1.2 on 2024-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfordonation',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('company', 'Company')], default='individual', max_length=20),
        ),
    ]
