# Generated by Django 5.1.2 on 2024-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_requestfordonation_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfordonation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
