# Generated by Django 5.1.2 on 2024-11-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='recipients.requestfordonation'),
        ),
    ]
